### ISSUE TITLE
IOS picker delegate issue

### ISSUE THREAD

**Issue by alexist** [nativescript-community/ui-document-picker#10]
This is the same issue as https://github.com/nativescript-community/ui-document-picker/issues/4, first workaround doesn't seems to fix the issue

Sometimes, on ios, selected file is not returned to application. I put some console.log in all DocumentPickerDelegate delegate function, and nothing is logged when this issue happen (documentPickerDidPickDocumentAtURL, 
documentPickerDidPickDocumentsAtURLs, ...)

Moving variable `let delegate;` outside openFilePicker function seems to fix the issue, but i'm not 100% sure as error happen randomly
![image](https://user-images.githubusercontent.com/812237/130588682-a1610523-067a-405b-8ebc-5b4cf117ff79.png)

**Comment by farfromrefug** [comment]
@alexist thanks !
