### ISSUE TITLE
Example of extensions to be passed? mimetypes or just suffixes?

### ISSUE THREAD

**Issue by t1amat9409** [nativescript-community/ui-document-picker#2]
Just a quick question.

Do I use mimetypes: eg. `["application/msword"]`
OR use it like this `['.doc', '.docx']?`

**Comment by farfromrefug** [comment]
@t1amat9409 sorry did not have the time to make a doc yet
```
const result = await openFilePicker({
                //@ts-ignore
                extensions: global.isIOS ? [kUTTypeData, kUTTypeContent, kUTTypeItem] : ['*/*'],
                multipleSelection: false,
                pickerMode: 0
            });
```
Something like that so:
* ios: use https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html#//apple_ref/doc/uid/TP40001319-CH202-CHDHIJDE
* android: use mimetype

**Comment by t1amat9409** [comment]
@farfromrefug  ah, thanks man... Will try it out

**Comment by t1amat9409** [comment]
@farfromrefug  I think `["pdf", "doc"]` works well with this,  instead of `["application/msword"]`

**Comment by farfromrefug** [comment]
@t1amat9409 you mean on android?

**Comment by t1amat9409** [comment]
@farfromrefug  my bad, I noticed after a while that all file are greyed out

**Comment by alexist** [comment]
The extensions filter is working only with one extension  ["pdf"] or ["png"], but not with multiple extensions. Android API seems to have changed, and you need something like :

```
      intent.putExtra(Intent.EXTRA_MIME_TYPES, acceptTypes);
 ```

**Comment by alexist** [comment]
I made a PR https://github.com/nativescript-community/ui-document-picker/pull/3 to fix the issue. It would be nice if you can review it, and merge this fix.

**Comment by alexist** [comment]
version 1.1.4 fix the issue.

This sample code work on ios and android. In android, you have to specify extension, android will find application mimetype related to the extension provided :
       
        const options: FilePickerOptions = {
            extensions       : isIOS ? [kUTTypeJPEG, kUTTypePDF] : ['jpeg', 'pdf'],
            multipleSelection: false
        };

**Comment by t1amat9409** [comment]
@alexist Awesome

**Comment by xpalacincreditoh** [comment]
I try with:

`extensions: isIOS ? [kUTTypePDF, kUTTypeText, kUTTypePlainText, "doc", "com.microsoft.word.doc", "org.openxmlformats.wordprocessingml.document"] : [],`

and only enable selection for PDF

**Comment by farfromrefug** [comment]
@xpalacincreditoh Please stop spamming this github repo! If you have question github is not the place. You should use Nativescript discord. Github is only for issue reporting.
Also in the future please add details, and you can also add a few nice words like `please` or `thanks` ...

**Comment by xpalacincreditoh** [comment]
> @xpalacincreditoh Please stop spamming this github repo! If you have question github is not the place. You should use Nativescript discord. Github is only for issue reporting. Also in the future please add details, and you can also add a few nice words like `please` or `thanks` ...

Good morning,

I will try to query the errors this plugin gives me in NativeScript Discord.
The question was very similar to others that were before mine.

Thanks @farfromrefug
