### ISSUE TITLE
A problem occurred configuring root project 'ui_document_picker'

### ISSUE THREAD

**Issue by rudaz-bp** [nativescript-community/ui-document-picker#23]
Hello everyone. 

I'm using plugin ui_document_picker version 1.1.12 with nativescript 7. I test the application using android emulator target api 33.

Since this morning i cannot run my android project (ns run --device {deviceId}). I've got the following error and it looks like to problem come from the ui-doucment-picker plugin
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ui_document_picker'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:7.3..
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/7.3./gradle-7.3..pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/7.3./gradle-7.3..pom
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
Failed to build plugin @nativescript-community/ui-document-picker :
Error: Command gradlew.bat failed with exit code 1`

If i run with --stacktrace or --info or --debug, I do not have more informations.

Does anyone know how i can fix this issue ?

Kind regards

**Comment by farfromrefug** [comment]
@rudaz-bp what have you changed ?
